# Generated by Django 2.2.6 on 2020-02-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'UserAuth',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.UserAuth')),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('post_time', models.DateField()),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserAuth')),
            ],
            options={
                'db_table': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('post_time', models.DateField()),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Note')),
                ('replyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserAuth')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserAuth')),
            ],
            options={
                'db_table': 'Likes',
                'unique_together': {('user_id', 'note_id')},
            },
        ),
    ]
