# Generated by Django 2.2.6 on 2020-02-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='tag_id',
        ),
    ]
