# Generated by Django 2.2.6 on 2020-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200219_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='post_time',
            field=models.DateTimeField(),
        ),
    ]
