# Generated by Django 2.2.6 on 2020-03-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200220_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replyto',
        ),
    ]
