# Generated by Django 2.2.6 on 2020-04-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200330_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
